---
match_system_arguments: {'architecture': 'Architecture', 'credential': 'Credential', 'firmware': 'Firmware', 'host': 'Host', 'kernel_command_line': 'KernelCommandLine', 'kernel_version': 'KernelVersion', 'virtualization': 'Virtualization'}

netdev_arguments: {'mac_address': 'MACAddress', 'mtu_bytes': 'MTUBytes'}

bridge_arguments: {'ageing_time_sec': 'AgeingTimeSec', 'forward_delay_sec': 'ForwardDelaySec', 'priority': 'Priority', 'stp': 'STP'}
