name: Publish Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  image_details:
    runs-on: ubuntu-22.04
    outputs:
      image_base: ${{ steps.details.outputs.image_registry }}/${{ steps.details.outputs.registry_account }}/${{ steps.details.outputs.repo_name }}
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@v2
      with:
        base_image: python:bookworm-main
  publish_galaxy:
    runs-on: ubuntu-22.04
    needs:
    - image_details
    container:
      image: ${{ needs.image_details.outputs.image_base }}:main
    steps:
    - uses: actions/checkout@v3
    - uses: kpfleming/composite-actions/galaxy-publish-tox@v2
      with:
        galaxy_token: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        tag: ${{ github.ref_name }}
  publish_docs:
    runs-on: ubuntu-22.04
    needs:
    - publish_galaxy
    container:
      image: docker.io/python:3.11
    steps:
    - uses: actions/checkout@v3
      with:
        ref: docsite
        path: docsite
    - run: docsite/workflow-support/make_docs.sh
    - uses: EndBug/add-and-commit@v9
      with:
        cwd: docsite
        add: . --no-ignore-removal
        tag: docsite-${{ github.ref_name }} --force
        tag_push: --force
